<?php

namespace AppBundle\Repository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarModelRepository extends \Doctrine\ORM\EntityRepository
{
}
