<?php

namespace AppBundle\Repository;

/**
 * ScooterModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScooterModelRepository extends \Doctrine\ORM\EntityRepository
{
}
