security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin_scooters
            logout:
                path: logout
                target: login

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
