<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJknwogc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJknwogc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJknwogc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJknwogc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJknwogc\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jknwogc',
    'container.build_id' => '2b2099f2',
    'container.build_time' => 1528795781,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJknwogc');
